// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb2fSdCdD0N-9b8z2ycy5KbYuDcA7LoV0',
    appId: '1:5032981378:web:f203abda473a300a29959b',
    messagingSenderId: '5032981378',
    projectId: 'finder-app-dbcb8',
    authDomain: 'finder-app-dbcb8.firebaseapp.com',
    storageBucket: 'finder-app-dbcb8.appspot.com',
    measurementId: 'G-SG6P7CKL8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC02p8bxVUy_3r63zKYcMP4fBAtH-3EBsA',
    appId: '1:5032981378:android:e17b34af7f79730029959b',
    messagingSenderId: '5032981378',
    projectId: 'finder-app-dbcb8',
    storageBucket: 'finder-app-dbcb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdBjAFbqHTa0PyB9M-PjSkcLxz13Ucc0I',
    appId: '1:5032981378:ios:d633c00d9abe733c29959b',
    messagingSenderId: '5032981378',
    projectId: 'finder-app-dbcb8',
    storageBucket: 'finder-app-dbcb8.appspot.com',
    iosBundleId: 'com.finder.finderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdBjAFbqHTa0PyB9M-PjSkcLxz13Ucc0I',
    appId: '1:5032981378:ios:2cc3c578bb40776829959b',
    messagingSenderId: '5032981378',
    projectId: 'finder-app-dbcb8',
    storageBucket: 'finder-app-dbcb8.appspot.com',
    iosBundleId: 'com.finder.finderApp.RunnerTests',
  );
}
